title = "A Pausanias Commentary in Progress"
description = "A born-digital commentary on Pausanias' _Periegesis_"
bibliographies_directory = "bibliographies"
commentaries_directory = "commentaries"
editions_directory = "out/editions"
home_page = "pages/home.md"

[[static_pages]]
title = "About"
path = "/about"
file_path = "pages/about.md"

[[table_of_contents]]    
label = "Attica" 
urn = "urn:cts:greekLit:tlg0525.tlg001:1.1-1.1" 
ref = "Scroll I"

[[table_of_contents]]    
label = "Corinth" 
urn = "urn:cts:greekLit:tlg0525.tlg001:2.1-2.38" 
ref = "Scroll II"

[[table_of_contents]]    
label = "Laconia" 
urn = "urn:cts:greekLit:tlg0525.tlg001:3.1-3.26" 
ref = "Scroll III"

[[table_of_contents]]    
label = "Messenia" 
urn = "urn:cts:greekLit:tlg0525.tlg001:4.1-4.36" 
ref = "Scroll IV"

[[table_of_contents]]    
label = "Elis, Part 1" 
urn = "urn:cts:greekLit:tlg0525.tlg001:5.1-5.27" 
ref = "Scroll V"

[[table_of_contents]]    
label = "Elis, Part 2" 
urn = "urn:cts:greekLit:tlg0525.tlg001:6.1-6.26" 
ref = "Scroll VI"

[[table_of_contents]]    
label = "Achaea" 
urn = "urn:cts:greekLit:tlg0525.tlg001:7.1-7.27" 
ref = "Scroll VII"

[[table_of_contents]]    
label = "Arcadia" 
urn = "urn:cts:greekLit:tlg0525.tlg001:8.1-8.54"
ref = "Scroll VIII"

[[table_of_contents]]    
label = "Boeotia" 
urn = "urn:cts:greekLit:tlg0525.tlg001:9.1-9.41" 
ref = "Scroll IX"

[[table_of_contents]]    
label = "Phokis, Ozolian Lokris" 
urn = "urn:cts:greekLit:tlg0525.tlg001:10.1-10.38" 
ref = "Scroll X"

[[editions]]
description = "Pausanias *Hellados Periegesis*"
filename = "tlg0525.tlg001.perseus-grc2.xml"
label = "ed. Spiro"
urn = "urn:cts:greekLit:tlg0525.tlg001.perseus-grc2"
