title = "A Pausanias Commentary in Progress"
description = "A born-digital commentary on Pausanias' _Periegesis_"
bibliographies_directory = "bibliographies"
commentaries_directory = "commentaries"
editions_directory = "out/editions"

[[table_of_contents]]    
label = "Book 1 - Attica" 
urn = "urn:cts:greekLit:tlg0525.tlg001:1" 
ref = "1"

[[editions]]
description = "Pausanias *Hellados Periegesis*"
filename = "tlg0525.tlg001.perseus-grc2.xml"
label = "ed. Spiro"
urn = "urn:cts:greekLit:tlg0525.tlg001.perseus-grc2"
